name: check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies & Build
      run: make

    - name: Run check
      run: make check

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: tests/.phpunit.unit.cov.xml,tests/.phpunit.integration.cov.xml
