name: check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: actions/checkout@v3

      - if: ${{ matrix.php < 8.1 }}
        run: rm composer.lock

      - name: Install dependencies & build
        run: composer install && make

      - name: Run test
        run: make test -k

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: tests/.phpunit.unit.cov.xml,tests/.phpunit.integration.cov.xml
