name: check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - php: '7.3'
            env: { PHPSTANFLAGS: -q }
          - php: '7.4'
            env: { PHPSTANFLAGS: -q }
          - php: '8.0'
            env: { PHPSTANFLAGS: -q }
          - php: '8.1'
            env: { PHPSTANFLAGS: -q }
          - php: '8.2'
            env: {}

    env: ${{ matrix.config.env }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.config.php }}
          coverage: xdebug

      - uses: actions/checkout@v3

      - if: ${{ matrix.php < 8.1 }}
        run: rm composer.lock

      - name: Install dependencies & build
        run: composer install && make

      - name: Run check
        run: make check -k

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: tests/.phpunit.unit.cov.xml,tests/.phpunit.integration.cov.xml
